### ISSUE TITLE
Change the Range Values dynamically

### ISSUE THREAD

**Issue by rach12345** [tb/ng2-nouislider#68] opened 2017-03-17 11:39 UTC
I am using ng2-nouislider integrated with Angular 2 webpacks.
Below is how I have declared the slider:
************************************************************************************************************

![image](https://cloud.githubusercontent.com/assets/25843523/24041610/4a64682a-0b34-11e7-812d-155b6ee2fe96.png)

-> app.component.html
<!-Range Display-->
**{{smeRange[0]}}-{{smeRange[1]}}**

<!-Slider Component-->
**<nouislider [connect]="true" #sliderTest [config]="someRange2config" [min]="0" [max]="10"  [step]=0.01" [(ngModel)]="smeRange"></nouislider>**

-> app.component.ts
**smeRange=[0,10]
someRange2config: any = {
      behaviour: 'drag',
      pips: {
    mode: 'steps',
    density: 5
  }**
************************************************************************************************************

**I want the Range Display to get updated as and when I move the slider heads.
Currently, what I am observing is, if I select a slider thumb, move it, and leave the mouse(mouseup), then the values are getting updated.**

Is there any way to update the Range Values on the go?(i.e. on mousemove)

Thanks in advance.

**Comment by emonidi** [comment] 2017-03-24 07:47
There is the method nouislider.updateOptions() which supposedly make this. The problem is that with ng2nouislider you need to get a reference to the nouislider element manually after it intializes and it builds it's DOM. However this does not happens on component OnInit but a bit later. Also since ng2slider is not giving you access to neither the nouislider object nor an event when slider initialized. So far what I managed to do is to query the HTML element manually in the first execution on the update handler and then assign it to a class property after which with I've got access to the updateOptions method. Here is reference from the nouislider docs https://refreshless.com/nouislider/more/#section-update.
Good luck.

**Comment by imjustd** [comment] 2017-05-04 12:00
Any workaround for this?

**Comment by emonidi** [comment] 2017-05-04 13:00
<nouislider  #sliderRef></nouislider>
Then in your component declare the viewchild as:
@ViewChild('sliderRef') sliderRef;
after the slider renders (you'll have to look for the right component lifecycle method) 
this.sliderRef.slider will return to you the noUiSlider object with all the methods which are in the original noUiSlider

**Comment by ruant** [comment] 2017-06-09 09:16
@emonidi Thanks! This should be documented in the docs.

**Comment by ejasarevic** [comment] 2017-08-23 16:42
@emonidi Thanks :)

**Comment by fergalddaly** [comment] 2017-09-04 21:12
Any chance that you might public the code so we can see how this can be achieved ?

**Closed** 2017-10-21 21:50 UTC

**Comment by almcaffee** [comment] 2017-11-24 02:01
Nay examples of this? I get the nouislider refs but ive tried a bunch of different ways and keep getting javascript errors like "slider.slide is not a function"

`
@ViewChildren('slider') slider: QueryList<any>;

this.slider.forEach(slider => {
      console.log(slider)
     //How do you listen for the slide event???
});`

**Comment by emonidi** [comment] 2017-11-24 08:42
It was quite a while ago when I used the slider but I remember that you
need to assign the slider when the component in which you are using it has
already been rendered.

**Comment by almcaffee** [comment] 2017-11-24 16:08
Yeah I know, im doing this in ngAfterViewInit() function

**Comment by emonidi** [comment] 2017-11-24 21:47
Why dont you console.log(slider) and see what's in there. If the slider
object is undefined which is probably not then slide may be really not a
function. If slider is defined and it's an object. Probably you should read
a little bit more documentation.

**Comment by adityaitsrkr** [comment] 2018-05-31 04:09
Hi alamcaffe,
Did you find a solution . If so can you pls share the code.
